In [16]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

In [17]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split 
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
%matplotlib inline

In [18]:
digit = load_digits()
x = digit.data
y = digit.target

In [19]:
x.shape, y.shape

((1797, 64), (1797,))

# Dataset is spliting into the training and testing sets

In [20]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

#  Logistic Regression

In [21]:
reg = LogisticRegression()
reg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [22]:
pred = reg.predict(X_test)

In [23]:
result = pd.DataFrame({"Predicted":pred,"Actual":y_test})

In [24]:
result.head()

Predicted  Actual
0          5       5
1          7       7
2          0       0
3          4       4
4          1       1

In [25]:
reg.score(X_test,y_test)*100

96.29629629629629

# Classification accuracy

In [26]:
from sklearn.metrics import classification_report

In [27]:
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        53
          1       0.91      0.93      0.92        56
          2       1.00      1.00      1.00        47
          3       0.97      0.98      0.97        59
          4       0.98      0.96      0.97        50
          5       1.00      0.90      0.95        50
          6       1.00      0.98      0.99        55
          7       0.96      0.98      0.97        56
          8       0.87      0.96      0.91        49
          9       0.95      0.94      0.95        65

avg / total       0.96      0.96      0.96       540



In [48]:
from sklearn import model_selection

In [49]:
kfold = model_selection.KFold(n_splits=10, random_state = 7)

In [50]:
resultss_2 = model_selection.cross_val_score(reg,x,y,cv=kfold,scoring='accuracy')

In [51]:
resultss_2

array([0.90555556, 0.95      , 0.89444444, 0.91666667, 0.94444444,
       0.97222222, 0.97777778, 0.95530726, 0.8603352 , 0.93854749])

In [52]:
resultss_2.sum()/10

0.931530105524519

# Logarithmic loss

In [53]:
loss = model_selection.cross_val_score(reg,x,y,cv=kfold,scoring='neg_log_loss')

In [54]:
loss

array([-0.45798961, -0.14435058, -0.61749705, -0.27323142, -0.27594697,
       -0.12815811, -0.11024468, -0.1233365 , -0.62592303, -0.68553964])

In [55]:
loss.sum()/10

-0.3442217575018163

# R2 metrics

In [56]:
r2_metrcs = model_selection.cross_val_score(reg,x,y,cv=kfold,scoring='r2')

In [57]:
r2_metrcs

array([0.73184699, 0.86942354, 0.81023661, 0.79423609, 0.82434177,
       0.94343263, 0.92524112, 0.90725247, 0.60169024, 0.82555495])

In [58]:
r2_metrcs.sum()/10

0.8233256404108781

# Mean absolute error

In [59]:
mean_absolute_error(y_test, pred)

0.16111111111111112

# Mean squared error

In [60]:
mean_squared_error(y_test, pred)

0.8685185185185185

# Confusion matrix

In [61]:
print(confusion_matrix(y_test, pred))

[[53  0  0  0  0  0  0  0  0  0]
 [ 0 52  0  1  0  0  0  0  2  1]
 [ 0  0 47  0  0  0  0  0  0  0]
 [ 0  0  0 58  0  0  0  0  1  0]
 [ 0  0  0  0 48  0  0  0  0  2]
 [ 0  2  0  0  0 45  0  1  2  0]
 [ 0  1  0  0  0  0 54  0  0  0]
 [ 0  0  0  0  1  0  0 55  0  0]
 [ 0  2  0  0  0  0  0  0 47  0]
 [ 0  0  0  1  0  0  0  1  2 61]]


In [62]:
accuracy_score(y_test, pred)

0.9629629629629629

# Classification report

In [63]:
print(classification_report(y_test, pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        53
          1       0.91      0.93      0.92        56
          2       1.00      1.00      1.00        47
          3       0.97      0.98      0.97        59
          4       0.98      0.96      0.97        50
          5       1.00      0.90      0.95        50
          6       1.00      0.98      0.99        55
          7       0.96      0.98      0.97        56
          8       0.87      0.96      0.91        49
          9       0.95      0.94      0.95        65

avg / total       0.96      0.96      0.96       540

